[package]
name = "heir-sweep-poc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2"
borsh = { version = "1", features = ["derive"] }

[dev-dependencies]
solana-program-test = "2"
solana-sdk = "2"
solana-client = "2"
tokio = { version = "1", features = ["full"] }
bincode = "1"
